name: decoar
description: An application that supports purshasing power and developes individuals' financial resources.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localization: ^0.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: "assets/imgs/logo.png"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.7
flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/l10n/
    - assets/lottie/
  fonts:
    - family: Cairo
      fonts:
       - asset: assets/fonts/Cairo.ttf
    - family: Tajawal
      fonts:
       - asset: assets/fonts/Tajawal.ttf